# Generated by Django 5.2.3 on 2025-06-11 02:55

from django.db import migrations

def cargar_talles(apps, schema_editor):
    Talle = apps.get_model('tienda', 'Talle')
    for nombre in ['XS', 'S', 'M', 'L', 'XL']:
        Talle.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_talles),
    ]
