# Generated by Django 5.2.3 on 2025-06-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20250610_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='123456', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password2',
            field=models.CharField(default='123456', max_length=100),
        ),
    ]
