# Generated by Django 5.2.3 on 2025-06-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cliente_password_cliente_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password2',
            field=models.CharField(max_length=100),
        ),
    ]
